# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c4cd55cefa879f8a2cfc6947239a8d07b8aa796ce4d4ab3f2dbf52e7c77181ff7be9a4a7794f9607d9c037c16464ab825804187d4a712b3aeb362a0a08893f3

test:
  secret_key_base: 57da824ed886220b81ffcc1d73203ec2862e0af9cafb40a0d3994eb24cc0e6516823bdf9c71625fca61b5870a46985418863462e1cfb587f9054b1cfb6cd787f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
